import axios from 'axios'
import React, { useState } from 'react'
import QRCode from "react-qr-code";

function PaytmQR() {
    const [amount, setAmount] = useState()
    const [qrData, setQrData] = useState()
    const [paytmQrImage, setPaytmQrImage] = useState()

    const handleBtn = () => {
        console.log("QR Button clicked...")

        const payload = {
            "amount": amount
        }

        // axios.post('http://192.168.0.240:82/api/qr-transaction', payload)
        axios.post('http://203.129.217.245:80/api/qr-transaction', payload)
            .then((res) => {
                console.log("QR Generated", res)
                setQrData(res.data.data.body.qrData)
                setPaytmQrImage(res.data.data.body.image)

            })
            .catch((err) => ("Error/Exeption while generating Paytm QR", err))
    }

    return (
        <>
            <div className='m-5'>
                <p>
                    <input onChange={(e) => setAmount(e.target.value)} type="number" className='border border-black my-5' placeholder='Enter Amount here' />
                </p>
                <button className='border bg-sky-400 rounded-sm shadow-md py-2 px-4' onClick={handleBtn}> Payment QR </button>

                {qrData && <div>
                    <p>This is Generated By QR Data</p>
                    <p>QR Data :- {qrData}</p>

                    <QRCode
                        size={200}
                        // style={{ height: "auto", maxWidth: "100%", width: "100%" }}
                        value={qrData}
                        viewBox={`0 0 256 256`}
                    />
                </div>
                }

                {paytmQrImage && <div>
                    <p>This is Generated By Base64 to Image</p>
                    {/* <p>QR Data :- {paytmQrImage}</p> */}

                    <img className='h-40' src={`data:image/jpeg;base64,${paytmQrImage}`} />
                </div>
                }
            </div>
        </>
    )
}

export default PaytmQR